/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Aluguel } from '../../models/aluguel';

export interface AtualizarAluguel$Params {
  id: number;
      body: Aluguel
}

export function atualizarAluguel(http: HttpClient, rootUrl: string, params: AtualizarAluguel$Params, context?: HttpContext): Observable<StrictHttpResponse<Aluguel>> {
  const rb = new RequestBuilder(rootUrl, atualizarAluguel.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Aluguel>;
    })
  );
}

atualizarAluguel.PATH = '/api/alugueis/{id}';
