/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Aluguel } from '../../models/aluguel';

export interface GetAlugueis$Params {
}

export function getAlugueis(http: HttpClient, rootUrl: string, params?: GetAlugueis$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Aluguel>>> {
  const rb = new RequestBuilder(rootUrl, getAlugueis.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Aluguel>>;
    })
  );
}

getAlugueis.PATH = '/api/alugueis';
