/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Aluguel {
  concluido?: boolean;
  dataDevolucao?: string;
  dataRetirada?: string;
  id?: number;
  modeloMoto?: string;
  nomeCliente?: string;
  valorTotal?: number;
}
