/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Aluguel {

  /**
   * Indica se o aluguel foi concluído.
   */
  concluido?: boolean;

  /**
   * Data e hora da devolução.
   */
  dataDevolucao?: string | null;

  /**
   * Data e hora da retirada.
   */
  dataRetirada?: string;

  /**
   * ID do aluguel.
   */
  id?: number;

  /**
   * Modelo da motocicleta.
   */
  modeloMoto?: string;

  /**
   * Nome do cliente.
   */
  nomeCliente?: string;

  /**
   * Custo final do aluguel.
   */
  valorTotal?: number | null;
}
